# Generated by Django 4.0.3 on 2022-03-10 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('librarydb', '0002_borrowedbook_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerExtra',
        ),
    ]
