# Generated by Django 2.2.12 on 2022-03-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddIndex(
            model_name='dictionary',
            index=models.Index(fields=['word', 'definition'], name='dictionary__word_12b5c8_idx'),
        ),
    ]
